apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
     app: devops
spec:
  selector:
    app: devops
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
